### ISSUE TITLE
Add option to remove "drag indicator" bar for drawers

### ISSUE THREAD

**Issue by madaxen86** [corvudev/corvu#12]
It does not make sense to have that indicator on top when you set side to right or left.
So firstly it would be good to place the bar opposite of the chosen side and also have the option to remove it completely.

**Comment by GiyoMoon** [comment]
![image](https://github.com/corvudev/corvu/assets/36984337/dbd26042-df15-4f5f-9a3a-cabcd9bb5aed)
Do you mean this drag handle at the top? corvu itself is unstyled and this handle is not added by default. You have to add it yourself and you also have full control over it.

**Comment by madaxen86** [comment]
Oh, sorry.
I am using the drawer of SoldUi. 
Didn't see that they have added the bar as by default
