### ISSUE TITLE
[Bug]: Resizable altKey only is not respected by keyboard interaction

### ISSUE THREAD

**Issue by katywings** [corvudev/corvu#33]
### Bug description

If you use a keyboard to interact with Resizable handles it will not respect the altKey only mode.

### Reproduction Link

https://stackblitz.com/edit/github-yesqvf-gfs3wm?file=src%2Froutes%2Findex.tsx

### Reproduction Steps

1. Focus the right handle
2. Press arrows on your keyboard to resize the panel

### Expected behavior

Using the keyboard to change Resizable handles should respect the altKey only setting.

### Additional context

Thank you so much for this amazing collection of primitives 😊!

**Comment by GiyoMoon** [comment]
Thanks for reporting! Fixed in `@corvu/resizable@0.2.2`

**Comment by katywings** [comment]
@GiyoMoon Thank you 😊!
