### ISSUE TITLE
[Bug]: Unknown file extension /utils/dist/reactivity/index.jsx in solid-presence #645

### ISSUE THREAD

**Issue by z3phyro** [corvudev/corvu#34]
### Bug description

When running tests on a component made with Kobalte there is the following error

<img width="660" alt="image" src="https://github.com/corvudev/corvu/assets/15892894/9777b528-cb01-4312-8bb9-3699768ef939">

I could find out that it's related with the solid-presence package. The access to the main module is through a js file, but then it references jsx files. I was tinkering with it a bit and when changing the entry point to a jsx files it works for the test but not for the build or npm run dev and viceversa.

I've also noticed similar issue in solid-prevent-scroll package and the router package.

attached an image and the stackblitz example

### Reproduction Link

https://stackblitz.com/edit/github-xfdh2g-4fkfdg?file=package.json

### Reproduction Steps

1. Install kobalte.
2. Create a test based on a kobalte component
3. Run the tests

### Expected behavior

Tests should work without problem

**Comment by GiyoMoon** [comment]
Hey! Thanks for reporting this.
It seems like vitest tries to import packages over the solid export, even if the import happens inside a `.js` file, which is odd. To fix this on my side, I added solid exports for the `solid-presence` and `solid-prevent-scroll` package. Make sure to update these packages to their latest version and the test should work :)
[Fixed repro with updated dependencies](https://stackblitz.com/edit/github-xfdh2g-jgz66b?file=src%2Fcomponents%2Fbutton.test.jsx)

**Comment by z3phyro** [comment]
Awesome 🤩 ! Thank you so much.
I forgot to say before, congrats for such a good job with Corvu. Keep it up 🦾

**Comment by GiyoMoon** [comment]
Thank you very much! 😊
It's always motivating to hear such kind words 💜 🐦‍⬛
