### ISSUE TITLE
[Bug]: Chrome Error on Drawer Overlay: Blocked  aria-hidden

### ISSUE THREAD

**Issue by gnosticdev** [corvudev/corvu#52]
### Bug description

I havent seen this error before - but it appears to be on the `<Drawer.Overlay>` component. I was able to fix it by removing the `tabindex=''`, so perhaps the error arises if you set a tabindex and also hide an element from screen readers? 

I am not very well versed on this topic, so I will defer to you since you clearly know your stuff :)

### Reproduction Link

https://corvu.dev/docs/primitives/drawer/

### Reproduction Steps

1. Go to the [corvu drawer page](https://corvu.dev/docs/primitives/drawer/)
2. Open any drawer in the examples
3. Click outside the component (on the overlay) to dismiss
4. Observe error in Chrome dev console

https://github.com/user-attachments/assets/824e1312-ed85-4836-99d5-d0b300a2aa1a

### Expected behavior

Chrome [links the spec here](https://w3c.github.io/aria/#aria-hidden)

**Comment by GiyoMoon** [comment]
Hey! Good catch, it seems like the `tabindex` attribute slipped in there. No need for it to be on the overlay. I'll create a patch release to remove it. Thanks!

**Comment by GiyoMoon** [comment]
Released as `@corvu/dialog@0.2.3` :)
