### ISSUE TITLE
[Bug]: Unit tests failing with ResizeObserver  error

### ISSUE THREAD

**Issue by karolis-kniuksta-trimble** [corvudev/corvu#63]
### Bug description

Can't run unit tests. Getting error:
```
ReferenceError: ResizeObserver is not defined
 ❯ Object.eval node_modules/.pnpm/@corvu+utils@0.4.2_solid-js@1.8.17/node_modules/@corvu/utils/dist/create/size.jsx:12:22
     10|     const element = access(props.element);
     11|     if (!element) return;
     12|     syncSize(element);
       |                      ^
     13|     const observer = new ResizeObserver(resizeObserverCallback);
     14|     observer.observe(element);
```

It seems to be related to this code:
https://github.com/corvudev/corvu/blob/5aa1377a5c6bfc9ebb5154e6ea2a291b3eefda0c/packages/utils/src/create/size.ts#L16
Maybe `ResizeObserver` should be imported explicitly in in the file?

### Reproduction Link

https://stackblitz.com/edit/corvu-3ebvcs?file=src%2FApp.spec.tsx

### Reproduction Steps

run `vitest`

### Expected behavior

Test completes successfully.

**Comment by GiyoMoon** [comment]
Hey! From quickly searching about this issue, it seems like `ResizeObserver` isn't available in jsdom and you need to mock it.
See here: https://github.com/jsdom/jsdom/issues/3368
Could you try this an report back? Thanks!

**Comment by karolis-kniuksta-trimble** [comment]
Oh, I didn't realize ResizeObserver was of browser's API...

This helped, thanks!
